### ISSUE TITLE
Add link to site in repo description

### ISSUE THREAD

**Issue by MadLittleMods** [BramvdnHeuvel/Digital-Justice#1]
Make it easy for people to view the site from the source repo by adding a link to https://digital-justice.com/ to the repo description and readme.

**Comment by BramvdnHeuvel** [comment]
I'm actually planning on adding a link to this repository on the website as well.

Adding it to the [README](https://github.com/BramvdnHeuvel/Digital-Justice/blob/main/README.md) should be simple enough.

**Comment by MadLittleMods** [comment]
There is also a specific website field you can add which would be nice:

![](https://user-images.githubusercontent.com/558581/132070450-f85f1c56-9b70-40c9-b7a6-70d548b2f5d5.png)

**Comment by BramvdnHeuvel** [comment]
Sharp! The website has now been added to the front page of the repository.
